### ISSUE TITLE
connection issue between db container and app container 

### ISSUE THREAD

**Issue by vigneshindn** [jcavat/docker-lamp#8]
connection issue between db container and app container

**Comment by jcavat** [comment]
Come on ! Be more specific... This is not an issue.

**Comment by CharlesDerek** [comment]
When running the docker build, and compose.. The database (between mysql, phpmyadmin, and apache) doesn't run. They're multiple issues, but ill break them down below.

I have had no idea why 1 out of every 10 attempts to rebuild the network it decides to work.
The only thought I have is it possibly is timing out during the build proccess in docker containers. [UPDATE: Solved, was problem [A] ]

[A] **The MYSQL user "user" and/or "root" has no privaleges to enter phpmyadmin:**
   This is possibly due to phpmyadmin forcing us to make a new password after being build 
   (this is only an assumption I haven't proved, yet found online issues others where facing
   with newer phpmyadmin versions). I had to use root (root worked only when other issues below 
   didn't also occur during builds).

```
ERROR_LOGS from CLI:
db_1          | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/myDb.sql
db_1          | mysql: [Warning] Using a password on the command line interface can be insecure.
db_1          | ERROR 1396 (HY000) at line 1618: Operation CREATE USER failed for 'root'@'localhost'

```


   [SOLVED:]
   This was due to enabling root privaleges to make sql files work. **_Others online were posting 
      this as a solution online but it removes privaleges of "user" when building containers_**
   {
   CREATE USER 'root'@'localhost' IDENTIFIED BY 'local';
   GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
   }

[B] **Only reads the ./dump/myDb.sql (No other sql files inserted in the dump folder):
   It's possible others were struggling with this too, but dont use a sql file outside of myDb.sql
   I believe this is not an issue, yet more of just the way docker works in the execution
   of the yaml file. Since we need to specfy the Database we're using in the docker-compose
   for each service there's two fixes for this. 

   1) **_Create different mysql services_** with unique ports and inner-connecting them with each
         other to the same ports on apache and phpmyadmin (more complicated choice that takes 
         more proccessing, but useful if planning a larger application to build and scale).

            In docker-compose.. Use different localhost ports but same ones inside services
            EXAMPLE:
              # also linking these under main services (www and phpmyadmin)
              db1:
                  image: mysql:8.0
                  ports:
                     - "3306:3306"
              db2:
                  image: mysql:8.0
                  ports:
                     - "3307:3306"

   2) **_Modifying the myDb.sql to build other databases_** in the proccess after building the
myDb
         database. Use the methods below:
      
         CREATE DATABASE IF NOT EXISTS myDb;
         USE myDb;
            --use lines above for myDb, then place myDb tables data here:

         CREATE DATABASE IF NOT EXISTS nextDb;
         USE nextDb;
           --same process

         --Remember anything over 10mb can possibly cause a timeout during compose (fix in php.ini)
** I wrote out the problems then solutions underneath as i fixed them, Because I'm sure other will have the same issue when using this git.
   I must say this has been very useful, thank you [jcavat](https://github.com/jcavat/).
**

**Comment by jcavat** [comment]
I encouter such a problem once. I fixed the problem by changing the name of the root directory... I did'nt try to understand why the directory name change has a consequence on docker. It uses this name for the volume.
